name: Deploy Exported App To GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build app
      run: yarn build
      env:
        NEXT_PUBLIC_BASE_PATH: /dev-hub

    - name: Export app    
      run: yarn export
      env:
        NEXT_PUBLIC_BASE_PATH: /dev-hub

    - name: Create .nojekyll file
      run: touch ./out/.nojekyll

    - name: Deploy exported app to GitHub Pages branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out
